name: pr
channels:
  - pytorch
  - defaults
dependencies:
  - h5py=2.9.0
  - cvxopt=1.2
  - imageio=2.5
  - numpy=1.16
  - scipy=1.3
  - pandas=0.25
  - pillow=6.1
  - pip=19.2
  - plotly=3.6
  - python=3.7
  - pytorch=1.2
  - matplotlib=3.1
  - jupyter=1.0
  - scikit-learn=0.21
  - torchvision=0.4
  - scikit-image=0.15
  - torchtext=0.4
  - xlrd=1.2
  - pip:
    - plyfile==0.7
    - torchsummary==1.5
